---
all:
  children:
    # all vm's
    demo:
      hosts:
        demo1:
          ansible_host: 192.168.60.101
          ansible_port: 22
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
          ansible_user: vagrant
          private_ip: 10.0.1.11
        demo2:
          ansible_host: 192.168.60.102
          ansible_port: 22
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
          ansible_user: vagrant
          private_ip: 10.0.1.12
        haproxy:
          ansible_host: 192.168.60.103
          ansible_port: 22
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
          ansible_user: vagrant
          private_ip: 10.0.1.13
    # group for web servers
    web:
      hosts:
        demo1:
        demo2:
