---
- name: restart httpd
  service:
    name: httpd
    state: restarted
  become: True
  listen: "restart web services"

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
  become: True
  listen: "restart web services"
