---
- name: Ensure sshd is running and enabled
  service:
    name: sshd
    state: started
    enabled: True
  become: True

- name: Ensure group ssh-user exists
  group:
    name: ssh-user
    state: present
    system: True
  become: True

- name: Append ansible user in the ssh-user
  user:
    name: "{{ ansible_facts['user_id'] }}"
    append: True
    groups: ssh-user
  become: True

- name: Copy ssh configuration file
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
  become: True
  notify: Restart sshd service
